### ISSUE TITLE
Leap Motion Gesture Recognition

### ISSUE THREAD

**Issue by takuti** [Sushisushi-sandesu/sushi#12]
- [x] Survey how to recognize a gesture
  - https://developer.leapmotion.com/documentation/java/api/Leap.Gesture.html

**Comment by takuti** [comment]
ジェスチャーで写真撮れれば終了。頼む！！！

**Comment by ganmacs** [comment]
:ok_woman:

**Comment by takuti** [comment]
At #22, Oculus team creating
- open canvas
- take a screenshot
- close canvas

event detectors.

なので
- [ ] 起動（キャンバス出す）時のジェスチャ
- [ ] 写真取るジェスチャ
- [ ] 終了（キャンパス消す）時のジェスチャ

のそれぞれを @Sushisushi-sandesu/leap-team で１人一つずつ実装する。

知見があればここで議論する :arrow_down:

**Comment by takuti** [comment]
- 起動時：[KeyTapGesture](https://developer.leapmotion.com/documentation/java/api/Leap.KeyTapGesture.html#javaclasscom_1_1leapmotion_1_1leap_1_1_key_tap_gesture)
- 写真とる：✌ by @ganmacs 
- 終了時：[SwipeGesture](https://developer.leapmotion.com/documentation/java/api/Leap.SwipeGesture.html#javaclasscom_1_1leapmotion_1_1leap_1_1_swipe_gesture)

**Comment by takuti** [comment]
#30, #31, #32
