### ISSUE TITLE
Create Web Browser Window on Unity

### ISSUE THREAD

**Issue by takuti** [Sushisushi-sandesu/sushi#13]

**Comment by neetp7k9** [comment]
I will create a browser in Unity, make user be able to open the web page in oculus.

# function TODO
- open the google homepage in the unity
- be able to scroll the page
- I try awesomium to build web browser
- Tutorial -> http://labs.awesomium.com/unity3d-integration-tutorial-part-1/
- http://answers.awesomium.com/questions/topics/Unity.html

**Comment by takuti** [comment]
Hi @neetp7k9,

I heard about the difficulties of this task from @natezzz. So, we set a new goal, creating chat app without web browser; more specifically, we will create photo chatting app which can send photos taken by our camera app to another person wearing Oculus. The issue is #25.

You will tackle to this new goal with @natezzz, so please discuss with him and help each other. If you have any questions, please ask me or @natezzz freely.

For the reasons that I mentioned above, I would like to close this issue. Is it OK? If you have something to share, please comment here.

**Comment by neetp7k9** [comment]
I see, sorry for absent from meeting, I will discuss with @natezzz later

**Comment by takuti** [comment]
OK. Please comment here if you discussed with @natezzz and everything is clear.

**Comment by takuti** [comment]
@neetp7k9 Have you discussed Camera chatting app with @natezzz ? I would like to close this issue.

**Comment by neetp7k9** [comment]
Yea, I have discussed with @natezzz, please close the issue, thanks!

**Comment by takuti** [comment]
Ok, thanks!
